In [15]:
#first we extract the apple stock prices using moonshot by giving AAPL's stock id by specifiying the start and end date
from quantrocket import get_prices
start_date = '2023-01-01'
end_date = '2023-12-31'
prices = get_prices("usstock-free-1d", universes="usstock-free", start_date=start_date, end_date=end_date, fields=["Close"])
close_prices = prices['FIBBG000B9XRY4']
print(close_prices)

Field  Date      
Close  2023-01-03    124.2163
       2023-01-04    125.4975
       2023-01-05    124.1666
       2023-01-06    128.7352
       2023-01-09    129.2616
                       ...   
       2023-12-22    193.3533
       2023-12-26    192.8040
       2023-12-27    192.9038
       2023-12-28    193.3333
       2023-12-29    192.2846
Name: FIBBG000B9XRY4, Length: 250, dtype: float64


In [16]:
#Next, we convert this into percentage
data = close_prices.pct_change()
print(data)

Field  Date      
Close  2023-01-03         NaN
       2023-01-04    0.010314
       2023-01-05   -0.010605
       2023-01-06    0.036794
       2023-01-09    0.004089
                       ...   
       2023-12-22   -0.005547
       2023-12-26   -0.002841
       2023-12-27    0.000518
       2023-12-28    0.002226
       2023-12-29   -0.005424
Name: FIBBG000B9XRY4, Length: 250, dtype: float64


In [17]:
#Then, we classify the data using as BULL, FLAT, BEAR using the given conditions
values=[]

for i in data:
  if i>0.01:
    values.append(1)
  elif i > -0.01:
    values.append(0)
  else:
    values.append(-1)
print(values)

[-1, 1, -1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, -1, 0, 0, 1, 1, -1, 1, -1, 0, 0, 1, 0, 1, -1, 0, -1, 0, 0, -1, 0, 0, -1, 0, 1, 1, -1, 0, -1, -1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, -1, -1, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 1, -1, 1, 0, 1, 1, 0, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, 1, 0, -1, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, -1, -1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, -1, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0]


In [21]:
#Then, we find the portfolio value, optimal indices and the transition distribution table
import numpy as np
portfolio_value=0
optimal_index=[]
transition_matrix = np.zeros((3,3))

#determining portfolio value and transition matrix
for i in range(len(values)-1):
  if values[i]==0 and values[i+1]==1:
    portfolio_value+=1
    optimal_index.append(i)
  elif values[i]==0 and values[i+1]==-1:
    portfolio_value-=1
  transition_matrix[values[i]+1,values[i+1]+1]+=1

print("Portfolio value: ",portfolio_value)
print("\nOptimal indices: ",optimal_index)
print("\nTotal optimal indices: ",len(optimal_index))


#finding probability distribution using the transition matrix
prob_distribution = np.zeros_like(transition_matrix)
for i in range(len(transition_matrix)):
    s = np.sum(transition_matrix[i])
    if s!=0:
        prob_distribution[i]=transition_matrix[i]/s
        
print("\nTransition matrix: \n",prob_distribution)


Portfolio value:  17

Optimal indices:  [5, 7, 11, 15, 20, 27, 29, 40, 49, 51, 58, 60, 68, 78, 84, 87, 93, 99, 102, 107, 109, 112, 116, 119, 122, 132, 141, 159, 163, 176, 186, 190, 206, 208, 211, 215, 217, 231, 233, 237]

Total optimal indices:  40

Transition matrix: 
 [[0.13888889 0.72222222 0.13888889]
 [0.14649682 0.59872611 0.25477707]
 [0.125      0.67857143 0.19642857]]
